/**
 * Writes the handoff registries out as a JSON snapshot the app can render from
 * when Supabase isn't configured.
 *
 * Two uses:
 *   - `npm run dev` / `npm run build` with no credentials still produces the
 *     real site, so the design can be reviewed before a database exists.
 *   - CI can build and assert on SEO output without provisioning Postgres.
 *
 * Supabase remains the source of truth in production; this file is only read
 * when NEXT_PUBLIC_SUPABASE_URL is unset. It goes through the exact same
 * row-mapping and hydration functions as the real data path, so the shapes
 * cannot drift.
 *
 *   npm run snapshot
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { toLocation, toPost, toSite, toTravel } from '../src/lib/hydrate';
import type { LocationRow, PostRow, SiteRow, TravelRow } from '../src/lib/hydrate';
import {
  cityToRow,
  loadCities,
  loadI18nOverlays,
  loadPosts,
  loadSite,
  loadTravel,
  postToRow,
  siteToRow,
  travelToRow,
} from './registry';

const OUT = resolve(process.cwd(), 'src/data/registry-snapshot.json');
const STAMP = new Date().toISOString();

const [cities, posts, site, travel, enOverlays] = await Promise.all([
  loadCities(),
  loadPosts(),
  loadSite(),
  loadTravel(),
  loadI18nOverlays(),
]);

const snapshot = {
  generatedAt: STAMP,
  note: 'Generated by scripts/export-snapshot.mts. Used only when Supabase is unconfigured.',
  locations: Object.entries(cities).map(([k, c], i) =>
    toLocation({ ...cityToRow(k, c, i), updated_at: STAMP } as unknown as LocationRow)
  ),
  posts: Object.entries(posts).map(([k, p], i) =>
    toPost({ ...postToRow(k, p, i), updated_at: STAMP } as unknown as PostRow)
  ),
  site: toSite({ ...siteToRow(site, enOverlays), updated_at: STAMP } as unknown as SiteRow),
  travel: toTravel({ ...travelToRow(travel), updated_at: STAMP } as unknown as TravelRow),
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(snapshot, null, 2) + '\n', 'utf8');

console.log(
  `  ✓ snapshot → src/data/registry-snapshot.json ` +
    `(${snapshot.locations.length} locations, ${snapshot.posts.length} posts, ` +
    `${snapshot.travel.routes.length} travel routes)`
);
