/**
 * Signs in to Content Studio the way the owner will, in a real browser.
 *
 * `verify:admin` proves the gate turns the wrong people away. That is only half
 * an answer — a gate that rejects everyone passes it perfectly. This drives the
 * actual login form: types the credentials, submits, follows the redirect, and
 * checks the dashboard rendered with live data.
 *
 * Needs ADMIN_EMAIL / ADMIN_PASSWORD (the same pair `db:seed` bootstrapped) and
 * a running server:
 *
 *   npx next start -p 3100
 *   npm run qa:admin
 */
import { execSync, spawn } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { deflateSync } from 'node:zlib';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { config } from 'dotenv';

config({ path: '.env.local' });
config({ path: '.env' });

const CHROME = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const PORT = 9229;
const BASE = (process.env.QA_ORIGIN ?? 'http://localhost:3100').replace(/\/$/, '');
const EMAIL = process.env.ADMIN_EMAIL;
const PASSWORD = process.env.ADMIN_PASSWORD;

if (!EMAIL || !PASSWORD) {
  console.error('ADMIN_EMAIL / ADMIN_PASSWORD not set — cannot test the sign-in path.');
  process.exit(1);
}

/**
 * Frees the debugging port if a previous run died without cleaning up.
 *
 * By PID, never `taskkill /IM chrome.exe` — that closes every Chrome window the
 * person running the tests has open, which is a genuinely hostile thing for a
 * test script to do to its author.
 */
function freePort(port) {
  try {
    const out = execSync(`netstat -ano -p tcp | findstr LISTENING | findstr :${port}`, {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    const pids = [...new Set(out.trim().split(/\r?\n/).map((l) => l.trim().split(/\s+/).pop()))];
    for (const pid of pids.filter(Boolean)) {
      execSync(`taskkill /F /PID ${pid}`, { stdio: 'ignore' });
      console.log(`  · freed port ${port} (pid ${pid})`);
    }
  } catch {
    // Nothing listening — the normal case.
  }
}

freePort(PORT);

/**
 * A real image on disk for the upload test.
 *
 * `DOM.setFileInputFiles` takes a path, not a blob — which is the point: the
 * file arrives through the same channel a photo picked from the owner's disk
 * does, so the resize and conversion are genuinely exercised rather than
 * simulated.
 */
const SAMPLE_IMAGE = join(mkdtempSync(join(tmpdir(), 'cdp-img-')), 'qa-sample.png');
writeFileSync(SAMPLE_IMAGE, makePng(64, 64));

/**
 * Builds a valid PNG rather than pasting a base64 blob.
 *
 * The pasted one did not decode — "The source image could not be decoded" — and
 * a corrupt fixture fails identically to a broken uploader, which is the wrong
 * thing for this assertion to be ambiguous about. Generated bytes are checkable.
 */
function makePng(width, height) {
  const crcTable = Array.from({ length: 256 }, (_, n) => {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    return c >>> 0;
  });
  const crc = (buf) => {
    let c = 0xffffffff;
    for (const b of buf) c = crcTable[(c ^ b) & 0xff] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const chunk = (type, data) => {
    const len = Buffer.alloc(4);
    len.writeUInt32BE(data.length);
    const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
    const sum = Buffer.alloc(4);
    sum.writeUInt32BE(crc(body));
    return Buffer.concat([len, body, sum]);
  };

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // truecolour

  // One filter byte per scanline, then RGB triples.
  const raw = Buffer.alloc(height * (1 + width * 3));
  for (let y = 0; y < height; y++) {
    const row = y * (1 + width * 3);
    raw[row] = 0;
    for (let x = 0; x < width; x++) {
      const px = row + 1 + x * 3;
      raw[px] = (x * 4) % 256;
      raw[px + 1] = (y * 4) % 256;
      raw[px + 2] = 128;
    }
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

const profile = mkdtempSync(join(tmpdir(), 'cdp-admin-'));
const chrome = spawn(CHROME, [
  `--remote-debugging-port=${PORT}`,
  `--user-data-dir=${profile}`,
  '--headless=new',
  '--disable-gpu',
  '--no-first-run',
  'about:blank',
]);
chrome.stderr.on('data', () => {});

async function waitForCdp() {
  for (let i = 0; i < 60; i++) {
    try {
      const r = await fetch(`http://127.0.0.1:${PORT}/json/version`);
      if (r.ok) return (await r.json()).webSocketDebuggerUrl;
    } catch {
      /* not up */
    }
    await new Promise((r) => setTimeout(r, 300));
  }
  throw new Error('CDP never came up');
}

const ws = new WebSocket(await waitForCdp());
await new Promise((res, rej) => {
  ws.onopen = res;
  ws.onerror = rej;
});
let id = 0;
const pending = new Map();
ws.onmessage = (ev) => {
  const m = JSON.parse(ev.data);
  if (m.id && pending.has(m.id)) {
    const p = pending.get(m.id);
    pending.delete(m.id);
    if (m.error) p.reject(new Error(JSON.stringify(m.error)));
    else p.resolve(m.result);
  }
};
const send = (method, params = {}, sessionId) =>
  new Promise((resolve, reject) => {
    const i = ++id;
    pending.set(i, { resolve, reject });
    ws.send(JSON.stringify({ id: i, method, params, sessionId }));
  });

const { targetId } = await send('Target.createTarget', { url: 'about:blank' });
const { sessionId } = await send('Target.attachToTarget', { targetId, flatten: true });
await send('Page.enable', {}, sessionId);
await send('Runtime.enable', {}, sessionId);
// Network/resource failures land here, not in Runtime — a chunk that 404s never
// throws, it just never runs, and the page looks like a feature that stopped
// working.
await send('Log.enable', {}, sessionId);

/**
 * The page's own console and uncaught errors.
 *
 * Without this, a client component that fails to hydrate looks exactly like a
 * broken feature: the server-rendered markup is all present and correct, every
 * "is it on screen" assertion passes, and nothing reacts to input. The reason
 * is always in the browser console, which was being thrown away.
 */
const pageErrors = [];
ws.addEventListener('message', (ev) => {
  const m = JSON.parse(ev.data);
  if (m.method === 'Runtime.exceptionThrown') {
    const d = m.params?.exceptionDetails;
    pageErrors.push(`uncaught: ${d?.exception?.description ?? d?.text ?? 'unknown'}`);
  }
  if (m.method === 'Log.entryAdded' && ['error', 'warning'].includes(m.params?.entry?.level)) {
    const e = m.params.entry;
    pageErrors.push(`${e.source}: ${e.text}${e.url ? ` (${e.url})` : ''}`.slice(0, 400));
  }
  if (m.method === 'Runtime.consoleAPICalled' && ['error', 'warning'].includes(m.params?.type)) {
    const text = (m.params.args ?? [])
      .map((a) => a.value ?? a.description ?? '')
      .join(' ')
      .trim();
    if (text) pageErrors.push(`console.${m.params.type}: ${text.slice(0, 400)}`);
  }
});

/** Drains what the page has complained about since the last call. */
function drainPageErrors() {
  const out = pageErrors.splice(0, pageErrors.length);
  return [...new Set(out)];
}

let failures = 0;
const ok = (label, cond, detail = '') => {
  if (cond) console.log(`  ✓ ${label}`);
  else {
    failures++;
    console.error(`  ✗ ${label}${detail ? ` — ${detail}` : ''}`);
  }
};

async function go(path) {
  await send('Page.navigate', { url: BASE + path }, sessionId);
  await new Promise((r) => setTimeout(r, 1600));
}
async function evalIn(expr) {
  const { result, exceptionDetails } = await send(
    'Runtime.evaluate',
    { expression: expr, returnByValue: true, awaitPromise: true },
    sessionId
  );
  if (exceptionDetails) throw new Error(JSON.stringify(exceptionDetails));
  return result.value;
}

/**
 * Clicks the button whose label matches, and says what was on screen if none does.
 *
 * `[...].find(...).click()` throws "Cannot read properties of undefined" when
 * nothing matches, which names neither the button being looked for nor the ones
 * that exist — several minutes of a debugging session for one missing label.
 */
async function clickButton(pattern, timeoutMs = 10000) {
  const deadline = Date.now() + timeoutMs;
  let last = { seen: [] };

  // Polls rather than clicking once. A save runs inside `startTransition`, and
  // `isPending` stays true — so the button stays `loading`, therefore disabled —
  // for a moment after the status text has already changed to "Tersimpan".
  // Clicking on the first sight of that text raced the transition and hit a
  // disabled button. A person would simply wait until it was clickable.
  while (Date.now() < deadline) {
    const res = await evalIn(`(() => {
      const buttons = [...document.querySelectorAll('button')];
      const hit = buttons.find(b => ${pattern}.test(b.textContent));
      if (!hit) return { ok: false, seen: buttons.map(b => b.textContent.trim()) };
      if (hit.disabled) return { ok: false, disabled: true, seen: [hit.textContent.trim()] };
      hit.click();
      return { ok: true };
    })()`).catch(() => ({ ok: false, seen: ['(navigating)'] }));

    if (res.ok) return true;
    last = res;
    await new Promise((r) => setTimeout(r, 200));
  }

  throw new Error(
    last.disabled
      ? `button ${pattern} never became enabled — check for blocking validation issues`
      : `no button matching ${pattern}; on screen: [${last.seen.join(' | ')}]`
  );
}

/**
 * Types into a React-controlled field, found by its visible label.
 *
 * Retries until the form registers the change, because a fixed wait races
 * hydration: the element exists in the server-rendered HTML long before React
 * attaches its listeners, so setting `.value` succeeds, nothing reacts, and the
 * failure reads as "the counter is broken" rather than "the page was not ready".
 * Confirmed by the marker landing in the DOM while `dirty` never flipped.
 *
 * The unsaved-changes indicator is the signal, since that is precisely the
 * form admitting it saw the edit.
 */
async function setFieldByLabel(label, value, timeoutMs = 12000) {
  const deadline = Date.now() + timeoutMs;
  const script = `(() => {
    const lab = [...document.querySelectorAll('label.cs-label')].find(l => l.textContent.trim().startsWith(${JSON.stringify(label)}));
    if (!lab) return { ok: false, why: 'no field labelled ' + ${JSON.stringify(label)} };
    const el = document.getElementById(lab.htmlFor);
    if (!el) return { ok: false, why: 'label points at no element' };
    const proto = el.tagName === 'TEXTAREA' ? window.HTMLTextAreaElement.prototype : window.HTMLInputElement.prototype;
    Object.getOwnPropertyDescriptor(proto, 'value').set.call(el, ${JSON.stringify(value)});
    el.dispatchEvent(new Event('input', { bubbles: true }));
    return { ok: true };
  })()`;

  let why = 'the form never registered the change';
  while (Date.now() < deadline) {
    const res = await evalIn(script).catch(() => ({ ok: false, why: 'navigating' }));
    if (!res.ok) why = res.why;
    else {
      await new Promise((r) => setTimeout(r, 250));
      // If React re-rendered from unchanged state it will have overwritten the
      // value; if it never ran, the value is still what was set. The two look
      // identical from outside and mean completely different things.
      const held = await evalIn(`(() => {
        const lab = [...document.querySelectorAll('label.cs-label')].find(l => l.textContent.trim().startsWith(${JSON.stringify(label)}));
        const el = lab && document.getElementById(lab.htmlFor);
        return el ? el.value : null;
      })()`).catch(() => null);
      why =
        held === value
          ? 'the DOM kept the new value but React never re-rendered — the page is not hydrated'
          : `React overwrote the field back to ${JSON.stringify(held)} — state did not change`;
      const registered = await evalIn(
        '/belum disimpan/i.test(document.querySelector(".cs-bar-status")?.textContent ?? "")'
      ).catch(() => false);
      if (registered) return { ok: true };
    }
    await new Promise((r) => setTimeout(r, 250));
  }
  return { ok: false, why };
}

/** Reads a field's value by its visible label. */
const fieldValueByLabel = (label) => `(() => {
  const lab = [...document.querySelectorAll('label.cs-label')].find(l => l.textContent.trim().startsWith(${JSON.stringify(label)}));
  if (!lab) return null;
  const el = document.getElementById(lab.htmlFor);
  return el ? el.value : null;
})()`;

/**
 * Polls until an expression is truthy.
 *
 * Discarding a draft ends in `location.reload()`, so a fixed sleep followed by
 * `Page.navigate` raced the reload and evaluated against a document that was
 * being torn down — the assertion failed while the feature worked, which is the
 * worst kind of test. Waiting on the condition rather than on the clock also
 * makes the whole suite faster than the sleeps it replaces.
 */
async function waitFor(expr, timeoutMs = 12000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      if (await evalIn(expr)) return true;
    } catch {
      // Mid-navigation: the execution context is gone. Try again.
    }
    await new Promise((r) => setTimeout(r, 250));
  }
  return false;
}

/**
 * Types into a React-controlled input.
 *
 * Setting `.value` directly does not notify React — it reads from its own
 * descriptor, so the field looks filled and submits empty. Going through the
 * native setter and then dispatching `input` is what makes React see it.
 */
const typeInto = (selector, value) => `(() => {
  const el = document.querySelector(${JSON.stringify(selector)});
  if (!el) return false;
  const set = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
  set.call(el, ${JSON.stringify(value)});
  el.dispatchEvent(new Event('input', { bubbles: true }));
  return true;
})()`;

console.log(`\nContent Studio sign-in — ${BASE}`);

/**
 * Refuses to run against a server serving a build whose assets are gone.
 *
 * `npm run start` fails with EADDRINUSE when an older instance still holds the
 * port — and the shell reports nothing, because the old server answers every
 * request. It serves HTML from the build it loaded at startup while `.next` on
 * disk has since been replaced, so every chunk 400s and no page hydrates. From
 * inside the browser that is indistinguishable from a feature that stopped
 * working: the markup is all there, and nothing responds to input.
 *
 * One fetch rules it out, and names the cause instead of leaving it to be
 * inferred from six failing assertions.
 */
{
  const html = await (await fetch(`${BASE}/admin/login`)).text();
  // Any chunk will do, and the build does not always emit a `webpack-*.js` —
  // looking for that specific name made the check silently skip itself.
  const chunk = /\/_next\/static\/chunks\/[a-zA-Z0-9._-]+\.js/.exec(html)?.[0];
  if (chunk) {
    const res = await fetch(BASE + chunk);
    if (!res.ok) {
      console.error(
        `\n  ✗ the server is serving a stale build — ${chunk} returns ${res.status}.` +
          `\n      An older \`next start\` is probably still holding the port (EADDRINUSE).` +
          `\n      Stop it and start again; nothing below would be meaningful.\n`
      );
      chrome.kill();
      process.exitCode = 1;
      throw new Error('stale build');
    }
  }
}

/* ------------------------------------------------------------ the redirect */

console.log('\nreaching a protected page while signed out');

await go('/admin');
ok(
  'lands on the login form',
  (await evalIn('location.pathname')) === '/admin/login',
  `at ${await evalIn('location.pathname')}`
);
ok(
  'remembers where it was going',
  (await evalIn('new URLSearchParams(location.search).get("next")')) === '/admin',
  `next=${await evalIn('new URLSearchParams(location.search).get("next")')}`
);
ok('form has an email and a password field', await evalIn(
  '!!document.querySelector(\'input[type="email"]\') && !!document.querySelector(\'input[type="password"]\')'
));
ok(
  'password field is a real password field',
  await evalIn('document.querySelector(\'input[type="password"]\').autocomplete === "current-password"'),
  'password managers rely on this'
);

/* ------------------------------------------------------- a wrong password */

console.log('\nwrong credentials');

await evalIn(typeInto('input[type="email"]', EMAIL));
await evalIn(typeInto('input[type="password"]', 'definitely-not-the-password'));
await evalIn('document.querySelector("form").requestSubmit()');
await new Promise((r) => setTimeout(r, 2500));

ok('stays on the login form', (await evalIn('location.pathname')) === '/admin/login');
const alert = await evalIn('document.querySelector(\'[role="alert"]\')?.textContent ?? ""');
ok('shows an error', alert.length > 0, 'nothing was announced');
ok(
  'error does not reveal whether the account exists',
  !/tidak ditemukan|tidak terdaftar|belum ada/i.test(alert),
  `"${alert}"`
);
ok('the error is announced to assistive tech', await evalIn(
  '!!document.querySelector(\'[role="alert"]\')'
));

/* ------------------------------------------------------ the real password */

console.log('\ncorrect credentials');

await evalIn(typeInto('input[type="email"]', EMAIL));
await evalIn(typeInto('input[type="password"]', PASSWORD));
await evalIn('document.querySelector("form").requestSubmit()');
await new Promise((r) => setTimeout(r, 3000));

// Reports what the server actually said, not just where the browser ended up.
// A sign-in that silently bounces back to the form is the same observation for
// a wrong password, a missing allowlist row and a cookie that failed to stick —
// and the message on screen is what tells them apart.
{
  const at = await evalIn('location.pathname');
  const said = await evalIn('document.querySelector(\'[role="alert"]\')?.textContent?.trim() ?? ""');
  ok(
    'arrives at the dashboard',
    at === '/admin',
    said ? `bounced to ${at} — server said: "${said}"` : `at ${at}, and the form said nothing`
  );
}
ok(
  'the content list rendered real rows',
  (await evalIn('document.querySelectorAll(".cs-row").length')) > 0,
  'no entries — the query probably failed silently'
);
ok(
  'every row links to an editor',
  await evalIn('[...document.querySelectorAll(".cs-row")].every(a => /^\\/admin\\/(lokasi|artikel)\\//.test(new URL(a.href).pathname))'),
  'a row pointed somewhere unexpected'
);
ok(
  'the signed-in account is shown',
  (await evalIn('document.querySelector(".cs-topbar-end")?.textContent ?? ""')).includes(EMAIL),
  'no way to tell which account is in use'
);

/* -------------------------------------------------- the session persists */

console.log('\nsession');

await go('/admin');
ok(
  'a fresh navigation stays signed in',
  (await evalIn('location.pathname')) === '/admin',
  'the session did not survive a navigation'
);

// The site itself must be unaffected — the admin root layout is a separate
// document, and a signed-in session must not change what a landing page serves.
await go('/');
ok(
  'the public site still renders normally when signed in',
  (await evalIn('document.documentElement.lang')) === 'id' &&
    (await evalIn('!!document.querySelector("header")')),
  'admin chrome leaked into the public site'
);

/* ----------------------------------------------------------------- editing */

// Drives one full edit cycle against a real entry. The draft is discarded at
// the end, and nothing here can reach the live row — staging writes to
// `content_drafts`, and publishing does not exist yet.
console.log('\nediting a landing page');

await go('/admin');
const firstEditor = await evalIn(
  '(() => { const a = [...document.querySelectorAll(".cs-row")].find(x => x.href.includes("/admin/lokasi/")); return a ? new URL(a.href).pathname : null; })()'
);
if (!firstEditor) {
  // Everything below edits a real entry, so there is nothing to salvage — but
  // it stops here rather than throwing a DOM TypeError that describes the test
  // instead of the failure.
  console.error('\n  ✗ no entry to edit — sign-in did not reach the content list. Stopping.\n');
  failures++;
  await send('Target.closeTarget', { targetId });
  chrome.kill();
  process.exitCode = 1;
  throw new Error('cannot continue without a signed-in session');
}
await go(firstEditor);

ok('the editor opens', (await evalIn('!!document.querySelector(".cs-editor")')), `at ${firstEditor}`);
ok(
  'it shows a Google preview',
  await evalIn('!!document.querySelector(".cs-serp-title")'),
  'no SERP preview rendered'
);
ok(
  'structural fields are not editable here',
  await evalIn('!document.querySelector(\'input[value="city"]\') && !!document.querySelector(".ar-badge")'),
  'template/variant appear to be editable'
);

// The counter has to react to typing, or it is decoration. Targets the meta
// title by label rather than "first input that happens to have a counter" —
// several fields carry a hint, so position was never a reliable way to find it.
const MARKER = `QA draft marker ${Date.now()}`;
const counterOf = `(() => {
  const lab = [...document.querySelectorAll('label.cs-label')].find(l => l.textContent.trim().startsWith('Meta title'));
  const box = lab?.parentElement?.querySelector('.cs-count span:last-child');
  return box ? box.textContent : null;
})()`;

const beforeCount = await evalIn(counterOf);
const typed = await setFieldByLabel('Meta title', MARKER);

// One assertion covers both: the field took the text and the form noticed. They
// cannot be separated without reintroducing the hydration race.
ok(
  'typing is registered and announced as unsaved',
  typed.ok,
  typed.ok ? '' : `${typed.why}${drainPageErrors().map((e) => `\n      ${e}`).join('')}`
);

const afterCount = await evalIn(counterOf);
ok(
  'the character counter follows what is typed',
  afterCount !== null && afterCount !== beforeCount,
  `counter went from ${JSON.stringify(beforeCount)} to ${JSON.stringify(afterCount)}`
);

await clickButton(/simpan draf/i);
ok(
  'saving reports success',
  await waitFor('/tersimpan/i.test(document.querySelector(".cs-bar-status")?.textContent ?? "")'),
  await evalIn('document.querySelector(".cs-bar-status")?.textContent ?? "(nothing)"')
);

await go(firstEditor);
ok(
  'the draft survives a reload',
  /belum diterbitkan/i.test(await evalIn('document.querySelector(".cs-lede")?.textContent ?? ""')),
  'the editor reopened on the live version — the draft was lost'
);

// The property the whole draft table exists to guarantee. A staged edit must
// be invisible to every visitor until it is published — so the marker just
// saved must appear on no public page at all, not merely on the one being
// edited. Checked across the entire sitemap, because a landing page's copy also
// surfaces on the hub, the home page and the blog's city links.
{
  const sitemap = await (await fetch(`${BASE}/sitemap.xml`)).text();
  const paths = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => new URL(m[1]).pathname);
  let leaked = null;
  for (const path of paths) {
    const body = await (await fetch(BASE + path)).text();
    if (body.includes(MARKER)) {
      leaked = path;
      break;
    }
  }
  ok(
    `the staged edit reaches no public page (${paths.length} checked)`,
    leaked === null,
    `it leaked onto ${leaked}`
  );
}

await go('/admin');
ok(
  'the list marks the entry as having pending edits',
  await evalIn('!!document.querySelector(".cs-dot")'),
  'no draft marker in the list'
);
ok(
  'the marker is not colour alone',
  /editan belum diterbitkan/i.test(await evalIn('document.querySelector(".cs-dot")?.textContent ?? ""')),
  'the dot carries no text alternative'
);

// Put it back. `confirm()` is stubbed because a native dialog would block CDP.
await go(firstEditor);
// A native confirm() would block CDP outright, so it is stubbed rather than
// dismissed — the point being tested is what happens after the owner agrees.
await evalIn('window.confirm = () => true');
await clickButton(/buang draf/i);
ok(
  'discarding a draft restores the live version',
  await waitFor(
    '/versi yang sedang tayang/i.test(document.querySelector(".cs-lede")?.textContent ?? "")'
  ),
  await evalIn('document.querySelector(".cs-lede")?.textContent ?? "(nothing)"')
);

/* ------------------------------------------------------------ article body */

// Nothing is saved here. The article body is the one thing that had no editor
// at all, so this checks it exists and behaves; the publish round-trip below
// already proves the write path on a landing page.
console.log('\narticle body');

await go('/admin');
const firstArticle = await evalIn(
  '(() => { const a = [...document.querySelectorAll(".cs-row")].find(x => x.href.includes("/admin/artikel/")); return a ? new URL(a.href).pathname : null; })()'
);
ok('there is an article to open', Boolean(firstArticle), 'no article rows in the list');

if (firstArticle) {
  await go(firstArticle);
  ok(
    'the body is editable as sections',
    (await evalIn('document.querySelectorAll(".cs-listed-row").length')) >= 3,
    `${await evalIn('document.querySelectorAll(".cs-listed-row").length')} section rows — the editorial rule is at least 3`
  );
  ok(
    'each section exposes a heading and its paragraphs',
    await evalIn(`(() => {
      const labels = [...document.querySelectorAll('.cs-listed-row-body label.cs-label')].map(l => l.textContent.trim());
      return labels.some(l => l.startsWith('Judul bagian')) && labels.some(l => l.startsWith('Paragraf'));
    })()`),
    'a section row is missing its fields'
  );
  ok(
    'the city relation is a picker, not free text',
    await evalIn('document.getElementById("city")?.tagName === "SELECT"'),
    'a typo in the city key would become a dead internal link'
  );
}

/* ---------------------------------------------------------- site settings */

// Staged and discarded, never published. These fields are on all 31 pages, so
// a test that published them would be rewriting the whole site to prove a form
// works.
console.log('\nsite settings');

await go('/admin');
ok(
  'the nav offers Situs & Global',
  await evalIn('[...document.querySelectorAll(".cs-nav-link")].some(a => /situs/i.test(a.textContent))'),
  'no way to reach the global settings'
);
ok(
  'the current section is marked for assistive tech, not only in colour',
  await evalIn('!!document.querySelector(\'.cs-nav-link[aria-current="page"]\')'),
  'no aria-current on the nav'
);

await go('/admin/situs');
ok('the settings screen opens', await evalIn('!!document.querySelector(".cs-editor")'));
ok(
  'official numbers are listed as editable rows',
  (await evalIn('document.querySelectorAll(".cs-listed-row").length')) > 0,
  'no list rows rendered'
);
ok(
  'the main WhatsApp number is a picker, not free text',
  await evalIn('document.getElementById("wa-main")?.tagName === "SELECT"'),
  'an unlisted number could be typed in'
);

// Add / reorder / remove, the three things the handoff asks for.
const rowsBefore = await evalIn('document.querySelectorAll(".cs-listed-row").length');
await clickButton(/tambah/i);
await waitFor(`document.querySelectorAll(".cs-listed-row").length === ${rowsBefore + 1}`);
ok('adding a row works', (await evalIn('document.querySelectorAll(".cs-listed-row").length')) === rowsBefore + 1);

ok(
  'the first row cannot be moved up, the last cannot be moved down',
  await evalIn(`(() => {
    const ups = [...document.querySelectorAll('.cs-icon-btn[aria-label^="Naikkan"]')];
    const downs = [...document.querySelectorAll('.cs-icon-btn[aria-label^="Turunkan"]')];
    return ups[0]?.disabled === true && downs[downs.length - 1]?.disabled === true;
  })()`),
  'reorder buttons at the ends were enabled'
);

ok(
  'reorder and delete buttons say which row they act on',
  await evalIn(`[...document.querySelectorAll('.cs-icon-btn')].every(b => (b.getAttribute('aria-label') ?? '').length > 8)`),
  'icon-only buttons with no accessible name'
);

await evalIn('window.confirm = () => true');
await evalIn('document.querySelectorAll(\'.cs-icon-btn[aria-label^="Hapus"]\')[' + rowsBefore + '].click()');
await waitFor(`document.querySelectorAll(".cs-listed-row").length === ${rowsBefore}`);
ok('removing a row works', (await evalIn('document.querySelectorAll(".cs-listed-row").length')) === rowsBefore);

/* ------------------------------------------------------- fleet and uploads */

console.log('\nfleet, unit classes and gallery');

await go('/admin/armada');
ok('the fleet screen opens', await evalIn('!!document.querySelector(".cs-editor")'));
ok(
  'the fleet is listed as editable rows',
  (await evalIn('document.querySelectorAll(".cs-listed-row").length')) > 0,
  'no fleet rows rendered'
);
ok(
  'photos have an upload control, not just a path field',
  (await evalIn('document.querySelectorAll(".cs-upload").length')) > 0,
  'no upload controls'
);
ok(
  'the path stays editable alongside the upload button',
  await evalIn('!!document.querySelector(".cs-upload-row input.ar-field__input")'),
  'existing repo-asset filenames would become uneditable'
);

/*
 * A real upload, through the real control.
 *
 * This is the only assertion that exercises the `media admin write` Storage
 * policy — every other part of Content Studio would pass with that policy
 * broken, because nothing else writes to Storage. It picks a genuine file off
 * disk through `DOM.setFileInputFiles`, so the resize, the WebP conversion, the
 * browser client's session and the bucket policy all run exactly as they will
 * for the owner.
 *
 * The object is deleted afterwards. Nothing is saved, so the database is never
 * touched by it.
 */
let uploadedObject = null;
{
  await send('DOM.enable', {}, sessionId);

  const { result: handle } = await send(
    'Runtime.evaluate',
    { expression: 'document.querySelector(\'.cs-upload input[type="file"]\')', returnByValue: false },
    sessionId
  );

  if (!handle?.objectId) {
    ok('a photo can be uploaded', false, 'no file input on the fleet screen');
  } else {
    await send('DOM.setFileInputFiles', { files: [SAMPLE_IMAGE], objectId: handle.objectId }, sessionId);

    const landed = await waitFor(
      `!!document.querySelector('.cs-upload-row input.ar-field__input')?.value?.startsWith('fleet/')`,
      20000
    );

    const pathValue = await evalIn(
      'document.querySelector(".cs-upload-row input.ar-field__input")?.value ?? ""'
    );
    const problem = await evalIn(
      'document.querySelector(\'.cs-upload [role="alert"]\')?.textContent ?? ""'
    );

    ok('a photo uploads and returns a Storage path', landed, problem || `path is "${pathValue}"`);

    if (landed) {
      uploadedObject = pathValue;
      const shrunk = await evalIn(`(() => {
        const hints = [...document.querySelectorAll('.cs-upload .cs-hint')].map(h => h.textContent);
        return hints.find(h => /KB setelah dikecilkan/.test(h)) ?? '';
      })()`);
      ok('…and reports the size it was reduced to', /KB/.test(shrunk), shrunk || 'no size reported');
    }
  }
}

// The gallery ships empty — the section is hidden entirely when it is — so a
// row has to be added before there are fields to inspect. Nothing is saved.
{
  const added = await evalIn(`(() => {
    const legend = [...document.querySelectorAll('legend')].find(l => /galeri/i.test(l.textContent));
    const btn = legend?.parentElement?.querySelector('.cs-listed-head button');
    if (!btn) return false;
    btn.click();
    return true;
  })()`);
  ok('a gallery photo can be added', added, 'no add button in the gallery section');

  await waitFor(`(() => {
    const legend = [...document.querySelectorAll('legend')].find(l => /galeri/i.test(l.textContent));
    return (legend?.parentElement?.querySelectorAll('.cs-listed-row').length ?? 0) > 0;
  })()`);

  ok(
    'gallery rows require alt text',
    await evalIn(`(() => {
      const legend = [...document.querySelectorAll('legend')].find(l => /galeri/i.test(l.textContent));
      const labels = [...(legend?.parentElement?.querySelectorAll('.cs-label') ?? [])].map(l => l.textContent.trim());
      return labels.some(l => l.startsWith('Teks alternatif'));
    })()`),
    'a gallery row has no alt-text field'
  );
}

ok(
  'unit classes are editable for the overseas pages',
  await evalIn(`[...document.querySelectorAll('legend')].some(l => /kelas unit/i.test(l.textContent))`),
  'no unit-class section'
);

/* ------------------------------------------------------------ travel tariffs */

console.log('\nroutes and tariffs');

await go('/admin/travel');
ok('the tariff screen opens', await evalIn('!!document.querySelector(".cs-editor")'));
ok(
  'routes carry a price cell per unit',
  await evalIn(`(() => {
    const units = [...document.querySelectorAll('legend')].find(l => /^unit$/i.test(l.textContent.trim()))
      ?.parentElement?.querySelectorAll('.cs-listed-row').length ?? 0;
    const firstMatrix = document.querySelector('.cs-prices');
    if (!units || !firstMatrix) return false;
    // One label for the group plus one per unit.
    return firstMatrix.querySelectorAll('.cs-label').length === units + 1;
  })()`),
  'the price matrix does not match the unit list'
);

// The distinction the whole screen turns on: blank means "not served", which is
// filtered out, and zero would advertise a free trip.
{
  const before = await evalIn(`(() => {
    const cells = [...document.querySelectorAll('.cs-prices input.ar-field__input')];
    const filled = cells.find(c => c.value.trim());
    return filled ? filled.value : null;
  })()`);

  ok('at least one tariff is filled in to work with', Boolean(before), 'no priced cells found');

  if (before) {
    const cleared = await evalIn(`(() => {
      const cells = [...document.querySelectorAll('.cs-prices input.ar-field__input')];
      const el = cells.find(c => c.value.trim());
      const set = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
      set.call(el, '');
      el.dispatchEvent(new Event('input', { bubbles: true }));
      return true;
    })()`);

    await waitFor('/belum disimpan/i.test(document.querySelector(".cs-bar-status")?.textContent ?? "")');

    ok(
      'clearing a tariff marks the unit as not serving that route',
      cleared &&
        (await evalIn(`(() => {
          const cells = [...document.querySelectorAll('.cs-prices input.ar-field__input')];
          const empty = cells.find(c => !c.value.trim());
          const hint = empty?.closest('div')?.querySelector('.cs-hint')?.textContent ?? '';
          return /tidak melayani/i.test(hint);
        })()`)),
      'an emptied cell did not say what emptying it means'
    );
  }
}

ok(
  'origin codes are explained as ref-code fragments',
  await evalIn(`(() => {
    const hints = [...document.querySelectorAll('.cs-hint')].map(h => h.textContent);
    return hints.some(h => /kode referensi/i.test(h));
  })()`),
  'nothing says why the origin code matters'
);

// Nothing is saved on this screen — reload to drop the cleared cell.
await go('/admin/travel');

/* -------------------------------------------------------------- publishing */

/**
 * The only assertion that can prove publishing works is one that changes real
 * content and then looks at the public page. So this does exactly that, and
 * puts it back.
 *
 * The original value is captured first and restored through a second publish,
 * so a clean run leaves the database byte-identical. A failed run leaves a
 * visible marker in a meta title, which is recoverable and — on a site that is
 * still `noindex` — harmless. An assertion that avoided the risk would also
 * avoid testing the thing.
 */
console.log('\npublishing');

await go(firstEditor);
const slug = await evalIn(fieldValueByLabel('Slug (Indonesia)'));
const originalTitle = await evalIn(fieldValueByLabel('Meta title'));
const publishMarker = `QA terbit ${Date.now()}`;

ok('the entry has a slug and a meta title to work with', Boolean(slug && originalTitle), `slug=${slug}`);

async function saveAndPublish(title) {
  const t = await setFieldByLabel('Meta title', title);
  if (!t.ok) throw new Error(`could not set the meta title: ${t.why}`);
  await clickButton(/simpan draf/i);
  await waitFor('/tersimpan/i.test(document.querySelector(".cs-bar-status")?.textContent ?? "")');
  await evalIn('window.confirm = () => true');
  await clickButton(/terbitkan/i);
  return waitFor('/diterbitkan|gagal/i.test(document.querySelector(".cs-bar-status")?.textContent ?? "")');
}

await saveAndPublish(publishMarker);
const publishMessage = await evalIn('document.querySelector(".cs-bar-status")?.textContent ?? ""');
ok('publishing reports success', /diterbitkan/i.test(publishMessage), publishMessage);
ok(
  'it says how many pages were regenerated',
  /\d+ halaman diperbarui/i.test(publishMessage),
  publishMessage
);

// The point of the whole commit: the change is now on the public page, without
// waiting out the ISR window.
{
  const live = await (await fetch(`${BASE}/${slug}`)).text();
  ok(`the change is live on /${slug} immediately`, live.includes(publishMarker), 'the public page still shows the old title');
}

await go('/admin');
ok(
  'the pending-edits marker is gone once published',
  !(await evalIn('!!document.querySelector(".cs-dot")')),
  'the draft dot survived publication'
);

// Put the original back through the same path, which also proves publishing
// twice in a row works.
await go(firstEditor);
await saveAndPublish(originalTitle);
{
  const restored = await (await fetch(`${BASE}/${slug}`)).text();
  ok(
    'restoring the original publishes cleanly',
    restored.includes(originalTitle) && !restored.includes(publishMarker),
    'the page did not return to its original title — CHECK THE DATABASE'
  );
}

/* ------------------------------------------------------------- signing out */

console.log('\nsigning out');

await go('/admin');
await clickButton(/keluar/i);
await new Promise((r) => setTimeout(r, 2500));

ok(
  'returns to the login form',
  (await evalIn('location.pathname')) === '/admin/login',
  `at ${await evalIn('location.pathname')}`
);

await go('/admin');
ok(
  'and the session is really gone',
  (await evalIn('location.pathname')) === '/admin/login',
  'the dashboard was still reachable after signing out'
);

/* -------------------------------------------------------------------- done */

// Storage is not covered by the draft/publish cycle, so the test cleans up
// after itself explicitly. Left behind, these accumulate one orphan per run.
if (uploadedObject) {
  const [bucket, ...rest] = uploadedObject.split('/');
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const secret = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (url && secret) {
    const res = await fetch(`${url}/storage/v1/object/${bucket}/${rest.join('/')}`, {
      method: 'DELETE',
      headers: { apikey: secret, Authorization: `Bearer ${secret}` },
    });
    console.log(`  · uploaded test object ${res.ok ? 'removed' : 'left behind'} — ${uploadedObject}`);
  }
}

await send('Target.closeTarget', { targetId });
chrome.kill();

if (failures) {
  console.error(`\n${failures} check(s) failed.\n`);
  process.exit(1);
}
console.log('\nSign-in works end to end.\n');
process.exit(0);
